# Generated by Django 2.2.1 on 2020-09-14 15:08

import dataStorage.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True)),
                ('tag', models.CharField(max_length=140)),
                ('satuts', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='phoneBench',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=250)),
                ('modelNo', models.CharField(max_length=250, unique=True)),
                ('ram', models.CharField(max_length=250)),
                ('cpu', models.IntegerField(null=True)),
                ('ux', models.IntegerField(null=True)),
                ('ddd', models.IntegerField(null=True)),
                ('total', models.IntegerField(null=True)),
                ('nt', models.IntegerField(null=True)),
                ('net', models.IntegerField(null=True)),
                ('pt', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['-device', '-total'],
            },
        ),
        migrations.CreateModel(
            name='phoneData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('modelNo', models.CharField(max_length=250, unique=True)),
                ('network', models.CharField(max_length=250, null=True)),
                ('launch', models.CharField(max_length=250, null=True)),
                ('body', models.CharField(max_length=250, null=True)),
                ('display', models.CharField(max_length=250, null=True)),
                ('platform', models.CharField(max_length=250, null=True)),
                ('memory', models.CharField(max_length=250, null=True)),
                ('camera', models.CharField(max_length=250, null=True)),
                ('gpu', models.CharField(max_length=250, null=True)),
                ('dimension', models.CharField(max_length=250, null=True)),
                ('battery', models.CharField(max_length=250, null=True)),
                ('price', models.IntegerField(null=True)),
                ('picture', models.FileField(blank=True, upload_to=dataStorage.models.upload_location)),
            ],
            options={
                'ordering': ['-name', '-modelNo'],
            },
        ),
        migrations.CreateModel(
            name='phoneImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelNo', models.CharField(max_length=140, null=True)),
                ('picture', models.FileField(upload_to=dataStorage.models.upload_location)),
            ],
            options={
                'ordering': ['-modelNo'],
            },
        ),
        migrations.CreateModel(
            name='phoneWeb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('link', models.CharField(max_length=250)),
                ('NetworkTechnology', models.CharField(max_length=250)),
                ('Network2Gbands', models.CharField(max_length=250)),
                ('Network3Gbands', models.CharField(max_length=250)),
                ('Network4Gbands', models.CharField(max_length=250)),
                ('NetworkSpeed', models.CharField(max_length=250)),
                ('LaunchAnnounced', models.CharField(max_length=250)),
                ('LaunchStatus', models.CharField(max_length=250)),
                ('BodyDimensions', models.CharField(max_length=250)),
                ('BodyWeight', models.CharField(max_length=250)),
                ('BodyBuild', models.CharField(max_length=250)),
                ('BodySIM', models.CharField(max_length=250)),
                ('DisplayType', models.CharField(max_length=250)),
                ('DisplaySize', models.CharField(max_length=250)),
                ('DisplayResolution', models.CharField(max_length=250)),
                ('DisplayOption', models.CharField(max_length=250)),
                ('PlatformOS', models.CharField(max_length=250)),
                ('PlatformChipset', models.CharField(max_length=250)),
                ('PlatformCPU', models.CharField(max_length=250)),
                ('PlatformGPU', models.CharField(max_length=250)),
                ('MemoryCardslot', models.CharField(max_length=250)),
                ('MemoryInternal', models.CharField(max_length=250)),
                ('MemoryOption', models.CharField(max_length=250)),
                ('MainCameraTriple', models.CharField(max_length=250)),
                ('MainCameraFeatures', models.CharField(max_length=250)),
                ('MainCameraVideo', models.CharField(max_length=250)),
                ('SelfiecameraSingle', models.CharField(max_length=250)),
                ('SelfiecameraFeatures', models.CharField(max_length=250)),
                ('SelfiecameraVideo', models.CharField(max_length=250)),
                ('SoundLoudspeaker', models.CharField(max_length=250)),
                ('Sound35mmjack', models.CharField(max_length=250)),
                ('CommsWLAN', models.CharField(max_length=250)),
                ('CommsBluetooth', models.CharField(max_length=250)),
                ('CommsGPS', models.CharField(max_length=250)),
                ('CommsRadio', models.CharField(max_length=250)),
                ('CommsUSB', models.CharField(max_length=250)),
                ('FeaturesSensors', models.CharField(max_length=250)),
                ('BatteryOption', models.CharField(max_length=250)),
                ('BatteryCharging', models.CharField(max_length=250)),
                ('MiscColors', models.CharField(max_length=250)),
                ('MiscModels', models.CharField(max_length=250)),
                ('MiscSAR', models.CharField(max_length=250)),
                ('MiscSAREU', models.CharField(max_length=250)),
                ('MiscPrice', models.CharField(max_length=250)),
                ('TestsPerformance', models.CharField(max_length=250)),
                ('TestsDisplay', models.CharField(max_length=250)),
                ('TestsCamera', models.CharField(max_length=250)),
                ('TestsAudioquality', models.CharField(max_length=250)),
                ('TestsBatterylife', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PosTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=140)),
                ('text', models.CharField(max_length=140, unique=True)),
                ('posphone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PosTweet', to='dataStorage.phoneBench')),
            ],
        ),
        migrations.CreateModel(
            name='NeuTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=140)),
                ('text', models.CharField(max_length=140, unique=True)),
                ('neuphone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NeuTweet', to='dataStorage.phoneBench')),
            ],
        ),
        migrations.CreateModel(
            name='NegTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=140)),
                ('text', models.CharField(max_length=140, unique=True)),
                ('negphone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NegTweet', to='dataStorage.phoneBench')),
            ],
        ),
    ]
