# Generated by Django 2.2.1 on 2020-08-05 16:42

import dataStorage.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True)),
                ('tag', models.CharField(max_length=140, unique=True)),
                ('satuts', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='phoneBench',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=250)),
                ('modelNo', models.CharField(max_length=250, unique=True)),
                ('ram', models.CharField(max_length=250)),
                ('cpu', models.IntegerField(null=True)),
                ('ux', models.IntegerField(null=True)),
                ('ddd', models.IntegerField(null=True)),
                ('total', models.IntegerField(null=True)),
                ('nt', models.IntegerField(null=True)),
                ('net', models.IntegerField(null=True)),
                ('pt', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['-device', '-total'],
            },
        ),
        migrations.CreateModel(
            name='phoneData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('modelNo', models.CharField(max_length=250, unique=True)),
                ('network', models.CharField(max_length=250, null=True)),
                ('launch', models.CharField(max_length=250, null=True)),
                ('body', models.CharField(max_length=250, null=True)),
                ('display', models.CharField(max_length=250, null=True)),
                ('platform', models.CharField(max_length=250, null=True)),
                ('memory', models.CharField(max_length=250, null=True)),
                ('camera', models.CharField(max_length=250, null=True)),
                ('gpu', models.CharField(max_length=250, null=True)),
                ('dimension', models.CharField(max_length=250, null=True)),
                ('battery', models.CharField(max_length=250, null=True)),
                ('price', models.IntegerField(null=True)),
                ('picture', models.FileField(blank=True, upload_to=dataStorage.models.upload_location)),
            ],
            options={
                'ordering': ['-name', '-modelNo'],
            },
        ),
        migrations.CreateModel(
            name='phoneImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelNo', models.CharField(max_length=250, null=True)),
                ('picture', models.FileField(upload_to=dataStorage.models.upload_location)),
            ],
            options={
                'ordering': ['-modelNo'],
            },
        ),
        migrations.CreateModel(
            name='PosTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=140)),
                ('text', models.CharField(max_length=140, unique=True)),
                ('posphone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PosTweet', to='dataStorage.phoneBench')),
            ],
        ),
        migrations.CreateModel(
            name='NeuTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=140)),
                ('text', models.CharField(max_length=140, unique=True)),
                ('neuphone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NeuTweet', to='dataStorage.phoneBench')),
            ],
        ),
        migrations.CreateModel(
            name='NegTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=140)),
                ('text', models.CharField(max_length=140, unique=True)),
                ('negphone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NegTweet', to='dataStorage.phoneBench')),
            ],
        ),
    ]
