# Generated by Django 2.2.1 on 2020-09-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataStorage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='antutu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=140)),
                ('url', models.CharField(max_length=140)),
                ('type', models.CharField(max_length=140)),
            ],
        ),
        migrations.RenameField(
            model_name='phonebench',
            old_name='ddd',
            new_name='gpu',
        ),
        migrations.AddField(
            model_name='phonebench',
            name='mem',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='phonebench',
            name='month',
            field=models.CharField(default='month yyyy', max_length=140),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phonebench',
            name='net',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='phonebench',
            name='nt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='phonebench',
            name='pt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='phonedata',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='BatteryCharging',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='BatteryOption',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='BodyBuild',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='BodyDimensions',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='BodySIM',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='BodyWeight',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='CommsBluetooth',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='CommsGPS',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='CommsRadio',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='CommsUSB',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='CommsWLAN',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='DisplayOption',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='DisplayResolution',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='DisplaySize',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='DisplayType',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='FeaturesSensors',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='LaunchAnnounced',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='LaunchStatus',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='MainCameraFeatures',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='MainCameraTriple',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='MainCameraVideo',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='MemoryCardslot',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='MemoryInternal',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='MemoryOption',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='MiscColors',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='MiscModels',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='MiscPrice',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='MiscSAR',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='MiscSAREU',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='Network2Gbands',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='Network3Gbands',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='Network4Gbands',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='NetworkSpeed',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='NetworkTechnology',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='PlatformCPU',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='PlatformChipset',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='PlatformGPU',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='PlatformOS',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='SelfiecameraFeatures',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='SelfiecameraSingle',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='SelfiecameraVideo',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='Sound35mmjack',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='SoundLoudspeaker',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='TestsAudioquality',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='TestsBatterylife',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='TestsCamera',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='TestsDisplay',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='TestsPerformance',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='link',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
