# Generated by Django 2.2.1 on 2020-09-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataStorage', '0002_auto_20200915_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneweb',
            name='BatteryCharging',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='BatteryOption',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='BodyBuild',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='BodyDimensions',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='BodySIM',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='BodyWeight',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='CommsBluetooth',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='CommsGPS',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='CommsRadio',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='CommsUSB',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='CommsWLAN',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='DisplayOption',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='DisplayResolution',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='DisplaySize',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='DisplayType',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='FeaturesSensors',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='LaunchAnnounced',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='LaunchStatus',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='MainCameraFeatures',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='MainCameraTriple',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='MainCameraVideo',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='MemoryCardslot',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='MemoryInternal',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='MemoryOption',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='MiscColors',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='MiscModels',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='MiscPrice',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='MiscSAR',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='MiscSAREU',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='Network2Gbands',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='Network3Gbands',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='Network4Gbands',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='NetworkSpeed',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='NetworkTechnology',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='PlatformCPU',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='PlatformChipset',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='PlatformGPU',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='PlatformOS',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='SelfiecameraFeatures',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='SelfiecameraSingle',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='SelfiecameraVideo',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='Sound35mmjack',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='SoundLoudspeaker',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='TestsAudioquality',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='TestsBatterylife',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='TestsCamera',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='TestsDisplay',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='TestsPerformance',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='link',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phoneweb',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
