# Generated by Django 2.2.1 on 2020-08-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataStorage', '0002_auto_20200805_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cache',
            name='tag',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
