# Generated by Django 2.2.1 on 2020-09-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataStorage', '0003_auto_20200915_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonedata',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
