# Generated by Django 2.2.1 on 2020-08-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataStorage', '0003_auto_20200805_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneimg',
            name='modelNo',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
