# Generated by Django 2.2.1 on 2020-08-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataStorage', '0004_auto_20200805_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='phoneWeb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('link', models.CharField(max_length=250)),
                ('NetworkTechnology', models.CharField(max_length=250)),
                ('Network2Gbands', models.CharField(max_length=250)),
                ('Network3Gbands', models.CharField(max_length=250)),
                ('Network4Gbands', models.CharField(max_length=250)),
                ('NetworkSpeed', models.CharField(max_length=250)),
                ('LaunchAnnounced', models.CharField(max_length=250)),
                ('LaunchStatus', models.CharField(max_length=250)),
                ('BodyDimensions', models.CharField(max_length=250)),
                ('BodyWeight', models.CharField(max_length=250)),
                ('BodyBuild', models.CharField(max_length=250)),
                ('BodySIM', models.CharField(max_length=250)),
                ('DisplayType', models.CharField(max_length=250)),
                ('DisplaySize', models.CharField(max_length=250)),
                ('DisplayResolution', models.CharField(max_length=250)),
                ('DisplayOption', models.CharField(max_length=250)),
                ('PlatformOS', models.CharField(max_length=250)),
                ('PlatformChipset', models.CharField(max_length=250)),
                ('PlatformCPU', models.CharField(max_length=250)),
                ('PlatformGPU', models.CharField(max_length=250)),
                ('MemoryCardslot', models.CharField(max_length=250)),
                ('MemoryInternal', models.CharField(max_length=250)),
                ('MemoryOption', models.CharField(max_length=250)),
                ('MainCameraTriple', models.CharField(max_length=250)),
                ('MainCameraFeatures', models.CharField(max_length=250)),
                ('MainCameraVideo', models.CharField(max_length=250)),
                ('SelfiecameraSingle', models.CharField(max_length=250)),
                ('SelfiecameraFeatures', models.CharField(max_length=250)),
                ('SelfiecameraVideo', models.CharField(max_length=250)),
                ('SoundLoudspeaker', models.CharField(max_length=250)),
                ('Sound35mmjack', models.CharField(max_length=250)),
                ('CommsWLAN', models.CharField(max_length=250)),
                ('CommsBluetooth', models.CharField(max_length=250)),
                ('CommsGPS', models.CharField(max_length=250)),
                ('CommsRadio', models.CharField(max_length=250)),
                ('CommsUSB', models.CharField(max_length=250)),
                ('FeaturesSensors', models.CharField(max_length=250)),
                ('BatteryOption', models.CharField(max_length=250)),
                ('BatteryCharging', models.CharField(max_length=250)),
                ('MiscColors', models.CharField(max_length=250)),
                ('MiscModels', models.CharField(max_length=250)),
                ('MiscSAR', models.CharField(max_length=250)),
                ('MiscSAREU', models.CharField(max_length=250)),
                ('MiscPrice', models.CharField(max_length=250)),
                ('TestsPerformance', models.CharField(max_length=250)),
                ('TestsDisplay', models.CharField(max_length=250)),
                ('TestsCamera', models.CharField(max_length=250)),
                ('TestsAudioquality', models.CharField(max_length=250)),
                ('TestsBatterylife', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='cache',
            name='tag',
            field=models.CharField(max_length=140),
        ),
    ]
