# Generated by Django 2.2.1 on 2020-09-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataStorage', '0004_auto_20200915_0219'),
    ]

    operations = [
        migrations.CreateModel(
            name='antutu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=140)),
                ('url', models.CharField(max_length=140, unique=True)),
                ('type', models.CharField(max_length=140)),
            ],
        ),
    ]
