# Generated by Django 2.2.1 on 2020-09-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataStorage', '0005_antutu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antutu',
            name='url',
            field=models.CharField(max_length=140),
        ),
    ]
