# Generated by Django 2.2.1 on 2020-09-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataStorage', '0006_auto_20200915_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonebench',
            name='month',
            field=models.CharField(default='old yyyy', max_length=140),
            preserve_default=False,
        ),
    ]
