# Generated by Django 2.2.1 on 2020-09-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataStorage', '0007_phonebench_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebench',
            name='net',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='phonebench',
            name='nt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='phonebench',
            name='pt',
            field=models.IntegerField(default=0),
        ),
    ]
